import { Injectable } from '@angular/core';
import {
  Observable,
  of as observableOf,
} from 'rxjs';

import { ItemDataService } from '../../../core/data/item-data.service';
import { DSpaceObject } from '../../../core/shared/dspace-object.model';
import { Vocabulary } from '../../../core/submission/vocabularies/models/vocabulary.model';
import { VocabularyService } from '../../../core/submission/vocabularies/vocabulary.service';

/**
 * A service containing all the common logic for the components generated by the
 * {@link DsoEditMetadataValueFieldLoaderComponent}.
 */
@Injectable({
  providedIn: 'root',
})
export class DsoEditMetadataFieldService {

  constructor(
    protected itemService: ItemDataService,
    protected vocabularyService: VocabularyService,
  ) {
  }

  /**
   * Find the vocabulary of the given {@link mdField} for the given item.
   * In DSpace 7, vocabularies are not discovered by metadata field and collection,
   * but we can determine authority fields by their metadata field name and provide
   * a basic vocabulary-like configuration to enable authority field functionality.
   *
   * @param dso The item
   * @param mdField The metadata field
   */
  findDsoFieldVocabulary(dso: DSpaceObject, mdField: string): Observable<Vocabulary> {
    // Check if this field is a known authority field based on common patterns
    const authorityFields = [
      'dc.contributor.author',
      'dc.creator',
      'dc.contributor.editor',
      'dc.contributor.advisor',
      'dc.contributor.other',
      'dcterms.creator',
      'dcterms.contributor'
    ];

    if (authorityFields.includes(mdField)) {
      // Return a basic vocabulary configuration that enables authority field functionality
      const authVocabulary = new Vocabulary();
      authVocabulary.name = mdField; // Use original field name so VocabularyService can recognize it
      authVocabulary.id = 'authority-' + mdField.replace(/\./g, '-');
      authVocabulary.scrollable = false;
      authVocabulary.hierarchical = false;
      authVocabulary.preloadLevel = 0;
      authVocabulary.type = 'vocabulary';
      return observableOf(authVocabulary);
    }

    // For non-authority fields, return undefined to use regular text fields
    return observableOf(undefined);
  }
}
