import { Injectable } from '@angular/core';
import {
  Observable,
  of as observableOf,
} from 'rxjs';

import { DSpaceObject } from '../../../core/shared/dspace-object.model';
import { Vocabulary } from '../../../core/submission/vocabularies/models/vocabulary.model';

/**
 * Known authority-controlled metadata fields for ORCID integration
 */
const AUTHORITY_FIELDS = [
  'dc.contributor.author',
  'dc.creator',
  'dc.contributor.editor',
  'dc.contributor.advisor',
  'dc.contributor.other',
  'dcterms.creator',
  'dcterms.contributor',
];

/**
 * A service containing all the common logic for the components generated by the
 * {@link DsoEditMetadataValueFieldLoaderComponent}.
 */
@Injectable({
  providedIn: 'root',
})
export class DsoEditMetadataFieldService {

  /**
   * Find the vocabulary of the given {@link mdField} for the given item.
   * For known authority fields (ORCID), returns a basic vocabulary configuration
   * to enable authority field functionality without requiring a backend vocabulary endpoint.
   *
   * @param dso The item
   * @param mdField The metadata field
   */
  findDsoFieldVocabulary(dso: DSpaceObject, mdField: string): Observable<Vocabulary> {
    if (AUTHORITY_FIELDS.includes(mdField)) {
      const authVocabulary = new Vocabulary();
      authVocabulary.name = mdField;
      authVocabulary.id = 'authority-' + mdField.replace(/\./g, '-');
      authVocabulary.scrollable = false;
      authVocabulary.hierarchical = false;
      authVocabulary.preloadLevel = 0;
      authVocabulary.type = 'vocabulary';
      return observableOf(authVocabulary);
    }

    return observableOf(undefined);
  }
}
