@echo off
setlocal EnableDelayedExpansion
REM scripts/dspace-deploy.bat
REM Helper for the dspace-deploy skill. See .claude/skills/dspace-deploy/SKILL.md.
REM
REM Brings up / down a multi-instance-safe DSpace FE+BE stack via docker compose.
REM Every instance uses a single digit (1-9) to namespace ports, container names, subnets.
REM
REM Usage:
REM   scripts\dspace-deploy.bat [instance=7] [up|down|status|logs|rebuild] [tag=dspace-7_x]
REM
REM Examples:
REM   scripts\dspace-deploy.bat                   - up instance 7
REM   scripts\dspace-deploy.bat 6                 - up instance 6
REM   scripts\dspace-deploy.bat 7 rebuild         - force-recreate instance 7 with --build
REM   scripts\dspace-deploy.bat 7 down            - tear down instance 7 (volumes too)
REM   scripts\dspace-deploy.bat 7 status          - show container status
REM   scripts\dspace-deploy.bat 7 logs            - follow logs

set "INSTANCE=%~1"
set "ACTION=%~2"
set "TAG=%~3"
set "REMOTE_BE=%~4"

if "%INSTANCE%"=="" set "INSTANCE=7"
if "%ACTION%"=="" set "ACTION=up"
if "%TAG%"=="" set "TAG=dspace-7_x"
REM REMOTE_BE: if set (e.g. "dev-5.pc:84"), the FE bypasses the local BE and proxies to that host.
REM Useful for testing UI changes without seeding the local DB.

REM Validate instance is a single digit 1-9
echo %INSTANCE%| findstr /r "^[1-9]$" >nul
if errorlevel 1 (
    echo ERROR: INSTANCE must be a single digit 1-9, got: %INSTANCE%
    exit /b 1
)

REM Bind to 0.0.0.0 so both `localhost` (browser) and `host.docker.internal` (which on
REM Docker Desktop resolves to the host's LAN IP via the Windows hosts file) reach the same port.
REM If we bound to 127.0.0.1, the FE-container SSR call would work via the docker-gateway resolution,
REM but the browser's call would hit 192.168.x.x:port -> connection refused.
set "HOST_IP=0.0.0.0"
REM Subnet prefix: 10.10X.0.0/16 (X = INSTANCE digit). Stays out of the 172.2X.0.0/16
REM range used by other DSpace projects on the same host.
set "SUBNET_PREFIX=10.10%INSTANCE%"
set "PROJECT=dspace-%INSTANCE%"

REM Resolve repo root (scripts is one level below repo root)
pushd "%~dp0\.."
set "REPO_ROOT=%CD%"
popd

set "ENVFILE=%REPO_ROOT%\docker\.env.dspace-%INSTANCE%"
set "OVERRIDE=%REPO_ROOT%\docker\.override.dspace-%INSTANCE%.yml"

echo === dspace-deploy: instance=%INSTANCE% action=%ACTION% tag=%TAG% ===

REM Write env file (cmd writes without BOM)
(
    echo # Auto-generated by scripts/dspace-deploy.bat
    echo INSTANCE=%INSTANCE%
    echo HOST_IP=%HOST_IP%
    echo TIMEZONE=Europe/Bratislava
    echo.
    echo DSPACE_UI_IMAGE=dataquest/dspace-angular:%TAG%
    echo DSPACE_REST_IMAGE=dataquest/dspace:%TAG%
    echo DSPACE_DB_IMAGE=dataquest/dspace-postgres-pgcrypto:%TAG%
    echo DSPACE_SOLR_IMAGE=dataquest/dspace-solr:%TAG%
    echo.
    echo DSPACE_UI_NAMESPACE=/
    echo DSPACE_REST_NAMESPACE=/server
    echo.
    if defined REMOTE_BE (
        for /f "tokens=1,2 delims=:" %%a in ("%REMOTE_BE%") do (
            echo # Pointing FE at remote BE %REMOTE_BE% ^(useful for testing UI without seeding the local DB^)
            echo DSPACE_HOST=%%a
            echo DSPACE_REST_PORT=%%b
            echo REST_URL=http://%REMOTE_BE%/server
            echo UI_URL=http://host.docker.internal:400%INSTANCE%
        )
    ) else (
        echo # host.docker.internal so SSR ^(inside container^) and browser ^(on host^) both resolve
        echo DSPACE_HOST=host.docker.internal
        echo DSPACE_REST_PORT=808%INSTANCE%
        echo REST_URL=http://host.docker.internal:808%INSTANCE%/server
        echo UI_URL=http://host.docker.internal:400%INSTANCE%
    )
) > "%ENVFILE%"
echo Wrote %ENVFILE%

REM Write compose override (subnet + extra_hosts + correct pm2 config path)
REM
REM The base docker-compose.yml hardcodes the FE entrypoint to:
REM   /bin/sh -c "pm2-runtime start dspace-ui.json ..."
REM But locally-built images put that file at /app/docker/dspace-ui.json (see Dockerfile),
REM so pm2 exits ENOENT on first start and the container loops. Override the entrypoint
REM to point at the right path AND surface its output so failures are diagnosable.
(
    echo # Auto-generated by scripts/dspace-deploy.bat
    echo networks:
    echo   dspacenet:
    echo     ipam:
    echo       config:
    echo         - subnet: %SUBNET_PREFIX%.0.0/16
    echo services:
    echo   dspace:
    echo     environment:
    echo       proxies__P__trusted__P__ipranges: '%SUBNET_PREFIX%.0'
    echo       REST_URL: http://host.docker.internal:808%INSTANCE%/server
    echo       UI_URL: http://host.docker.internal:400%INSTANCE%
    echo       rest__P__cors__P__allowed__D__origins: 'http://host.docker.internal:400%INSTANCE%, http://localhost:400%INSTANCE%'
    echo   dspace-angular:
    echo     extra_hosts:
    echo       - host.docker.internal:host-gateway
    echo     entrypoint:
    echo       - /bin/sh
    echo       - -c
    echo       - if [ -f /app/dspace-ui.json ]; then pm2-runtime start dspace-ui.json; else pm2-runtime start docker/dspace-ui.json; fi
) > "%OVERRIDE%"
echo Wrote %OVERRIDE% (subnet %SUBNET_PREFIX%.0.0/16)

set COMPOSE_BASE=docker compose --env-file "%ENVFILE%" -p %PROJECT% -f "%REPO_ROOT%\docker\docker-compose.yml" -f "%REPO_ROOT%\docker\docker-compose-rest.yml" -f "%OVERRIDE%"

if /i "%ACTION%"=="status" (
    %COMPOSE_BASE% ps
    goto :eof
)
if /i "%ACTION%"=="logs" (
    %COMPOSE_BASE% logs --tail=200 -f
    goto :eof
)
if /i "%ACTION%"=="down" (
    echo === Tearing down [%PROJECT%] ===
    %COMPOSE_BASE% down -v --remove-orphans
    goto :eof
)

REM Default: up (or rebuild)
docker info --format "{{.ServerVersion}}" >nul 2>&1
if errorlevel 1 (
    echo ERROR: docker info failed - is Docker Desktop running?
    exit /b 1
)

if /i "%ACTION%"=="rebuild" (
    echo === Pulling ^& building [%PROJECT%] ===
    %COMPOSE_BASE% pull
    %COMPOSE_BASE% up -d --build --force-recreate --remove-orphans
) else (
    echo === Pulling images ===
    %COMPOSE_BASE% pull
    echo === Up [%PROJECT%] ===
    %COMPOSE_BASE% up -d --no-build --remove-orphans
)
if errorlevel 1 (
    echo ERROR: docker compose up failed
    exit /b 1
)

echo === Waiting for services to become ready ===
set "BE_URL=http://%HOST_IP%:808%INSTANCE%/server/api"
set "FE_URL=http://%HOST_IP%:400%INSTANCE%/"
set /a TRIES=0
:wait_loop
set /a TRIES+=1
if %TRIES% GTR 90 goto :ready_timeout

REM Use curl which is bundled with Windows 10+
for /f "tokens=*" %%i in ('curl -s -o nul -w "%%{http_code}" --max-time 4 "%BE_URL%" 2^>nul') do set "BE_CODE=%%i"
for /f "tokens=*" %%i in ('curl -s -o nul -w "%%{http_code}" --max-time 4 "%FE_URL%" 2^>nul') do set "FE_CODE=%%i"
echo   try %TRIES%: BE=%BE_CODE% FE=%FE_CODE%
if "%BE_CODE%"=="200" if "%FE_CODE%"=="200" goto :ready_ok

timeout /t 5 /nobreak >nul
goto :wait_loop

:ready_timeout
echo WARNING: services not fully ready (BE=%BE_CODE% FE=%FE_CODE%). Inspect: scripts\dspace-deploy.bat %INSTANCE% logs
goto :print_urls

:ready_ok
echo === Ready ===

:print_urls
echo.
echo === URLs ===
echo   UI:   %FE_URL%
echo   REST: %BE_URL%
echo   Solr: http://%HOST_IP%:898%INSTANCE%
echo   DB:   postgres://dspace:dspace@%HOST_IP%:543%INSTANCE%/dspace
endlocal
