# DSpace Docker deploy on dataquest servers
name: Deploy DSpace

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: dspace-dep-1
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false
      - name: deploy on port 86
        run: |
          cd $GITHUB_WORKSPACE/build-scripts/run/
          pwd

          touch .env.dev-5 || true
          echo INSTANCE=6 >> .env.dev-5
          echo DSPACE_HOST=dev-5.pc >> .env.dev-5
          echo DSPACE_VER=customer-TUL >> .env.dev-5
          echo DSPACE_SSL=false >> .env.dev-5
          echo DOCKER_OWNER=dataquest >> .env.dev-5
          echo DSPACE_UI_IMAGE=${DOCKER_OWNER}/dspace-angular:$DSPACE_VER >> .env.dev-5
          echo DSPACE_REST_IMAGE=${DOCKER_OWNER}/dspace:$DSPACE_VER >> .env.dev-5
          echo DSPACE_REST_PORT=8$INSTANCE >> .env.dev-5
          echo REST_URL=http://${DSPACE_HOST}:${DSPACE_REST_PORT}/server >> .env.dev-5
          echo UI_URL=http://${DSPACE_HOST}:400$INSTANCE >> .env.dev-5
          
          export ENVFILE=$(pwd)/.env.dev-5
          ./start.sh dspace-6
