name: Playwright tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  playwright-tests:
    runs-on: dspace-test-1
    timeout-minutes: 45
    steps:
      - name: Checkout Playwright tests
        uses: actions/checkout@v4
        with:
          repository: dataquest-dev/dspace-ui-tests
          path: dspace-ui-tests
          token: ${{ secrets.DEPLOY_DEV5_GH_ACTION_DISPATCH }}

      - name: test
        working-directory: dspace-ui-tests/scripts
        env:
          HOME_URL: http://dev-6.pc:8603/repository/
          NAME: LINDAT-9
        run: |
          ./test.sh

      - uses: mazoea/ga-maz/end@master
        with:
          CHOWN_DIR: ./
        if: ${{ always() }}